### ISSUE TITLE
Set execute on /etc/my_server_minecraft/bedrock_server

### ISSUE THREAD

**Issue by dynstatic** [bile0026/minecraft_bedrock_deploy#2]
It's permissions aren't execute after unzip.

```
$ ls -al
total 139823
drwxrwxr-x  6 minecraft minecraft        14 Nov 27 00:02 .
drwxr-xr-x 73 root      root            149 Nov 27 01:13 ..
-rw-r--r--  1 minecraft minecraft 364124664 Nov 27 00:02 bedrock_server
```

**Comment by bile0026** [comment]
> It's permissions aren't execute after unzip.
> 
> ```
> $ ls -al
> total 139823
> drwxrwxr-x  6 minecraft minecraft        14 Nov 27 00:02 .
> drwxr-xr-x 73 root      root            149 Nov 27 01:13 ..
> -rw-r--r--  1 minecraft minecraft 364124664 Nov 27 00:02 bedrock_server
> ```

Pushed a fix for this. Please let me know if you have a chance to test.
